<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PrivateAssets>all</PrivateAssets>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CodeHollow.FeedReader" Version="1.2.6" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RssApp.DataAccess\RssApp.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
    <Folder Include="Validations\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RssApp.Application.Tests" />
  </ItemGroup>
</Project>
